#!/usr/bin/env python3
"""
make_paper_assets.py — final step of the evidence pipeline.

Turns the JSON outputs in results/ into paper-ready assets so that every
number in the manuscript is traceable to a script output:

  results/paper/tab_quality.tex     full cohort vs head-slice signal quality
  results/paper/tab_date_audit.tex  ECG date extraction, meaning and co-registration
  results/paper/tab_gating.tex      diagnosis AUROC / HbA1c MAE per gate
  results/paper/tab_ablation.tex    modality ablation under G3
  results/paper/tab_benchmark.tex   measured runtimes vs the manual baseline
  results/paper/tab_usability.tex   usability study (if scored)
  results/paper/fig_offsets.pdf     ECG/CGM/visit offset distributions
  results/paper/fig_funnel.pdf      retention by study group across gates
  results/paper/fig_gating.pdf      AUROC per gate with 95% CIs and G3-rand
  results/paper/numbers.md          claim → value → source file and key

Missing inputs are skipped with a message. Assets built from the synthetic
fixture carry a "SYNTHETIC" watermark and header comment.

Usage
  python scripts/make_paper_assets.py
"""

from __future__ import annotations

from pathlib import Path

from _common import banner, read_json, results_dir

GROUP_SHORT = {
    "healthy": "Healthy",
    "pre_diabetes_lifestyle_controlled": "Pre-DM",
    "oral_medication_and_or_non_insulin_injectable_medication_controlled": "Oral Med.",
    "insulin_dependent": "Insulin",
}
VERDICT_SHORT = {"normal": "Normal", "otherwise_normal": "Otherwise normal",
                 "borderline": "Borderline", "abnormal": "Abnormal"}


class Assets:
    def __init__(self) -> None:
        self.dir = results_dir() / "paper"
        self.dir.mkdir(parents=True, exist_ok=True)
        self.numbers: list[tuple[str, str, str]] = []
        self.synthetic = False

    def note(self, claim: str, value, source: str) -> None:
        self.numbers.append((claim, str(value), source))

    def tex(self, name: str, body: str) -> None:
        head = "% Generated by scripts/make_paper_assets.py — do not edit by hand.\n"
        if self.synthetic:
            head += "% SYNTHETIC TEST DATA — NOT AI-READI RESULTS\n"
        (self.dir / name).write_text(head + body)
        print(f"  wrote {name}")

    def fig(self, fig, name: str) -> None:
        if self.synthetic:
            fig.text(0.5, 0.5, "SYNTHETIC", fontsize=28, color="0.85", ha="center", va="center",
                     rotation=30, zorder=0, alpha=0.6)
        fig.savefig(self.dir / name, bbox_inches="tight")
        print(f"  wrote {name}")


def ci(c) -> str:
    return f"[{c[0]}, {c[1]}]" if c and c[0] is not None else ""


def fmt(x, nd=1) -> str:
    return "--" if x is None else (f"{x:.{nd}f}" if isinstance(x, (int, float)) else str(x))


def plt_setup():
    import matplotlib
    matplotlib.use("Agg")
    import matplotlib.pyplot as plt
    plt.rcParams.update({"font.size": 8, "font.family": "serif", "axes.spines.top": False,
                         "axes.spines.right": False, "pdf.fonttype": 42, "ps.fonttype": 42})
    return plt


# ── Quality ──────────────────────────────────────────────────────────────────

def quality(a: Assets) -> None:
    q = read_json("quality_full.json")
    if not q:
        print("  skip quality (run full_cohort_quality.py)")
        return
    c, e, cmp_ = q["summary"]["cgm"], q["summary"]["ecg"], q["head_slice_comparison"]["metrics"]
    rows = []
    if c:
        thr = c["dropout_threshold_pct"]
        m = cmp_.get("cgm_pct_under_threshold") or {}
        rows.append(f"CGM dropout $<${thr:g}\\,\\% & {fmt(m.get('head_slice'))} & "
                    f"{fmt(c['pct_under_threshold'])} {ci(c['pct_under_threshold_ci95'])} & {fmt(m.get('p_value'), 3)} \\\\")
        rows.append(f"CGM mean dropout (\\%) & {fmt(cmp_.get('cgm_mean_dropout_pct', {}).get('head_slice'))} & "
                    f"{fmt(c['mean_dropout_pct'])} & -- \\\\")
        a.note("CGM participants analysed (full cohort)", c["n_sampled"], "quality_full.json: summary.cgm.n_sampled")
        a.note(f"CGM % with dropout < {thr:g}%", f"{c['pct_under_threshold']} {ci(c['pct_under_threshold_ci95'])}",
               "quality_full.json: summary.cgm.pct_under_threshold")
        a.note("CGM mean dropout % (observed span)", c["mean_dropout_pct"], "quality_full.json: summary.cgm.mean_dropout_pct")
        a.note("CGM mean dropout % (nominal 10-day wear)", c["mean_dropout_nominal_pct"],
               "quality_full.json: summary.cgm.mean_dropout_nominal_pct")
    if e:
        for v in ("normal", "otherwise_normal", "borderline", "abnormal"):
            full = next((x for x in e["verdicts"] if x["verdict"] == v), None)
            m = cmp_.get(f"ecg_pct_{v}") or {}
            if full:
                rows.append(f"ECG verdict: {VERDICT_SHORT[v]} & {fmt(m.get('head_slice'))} & "
                            f"{fmt(full['pct'])} {ci(full['ci95'])} & {fmt(m.get('p_value'), 3)} \\\\")
                a.note(f"ECG % {VERDICT_SHORT[v]} (full cohort)", f"{full['pct']} {ci(full['ci95'])}",
                       f"quality_full.json: summary.ecg.verdicts[{v}]")
        a.note("ECG participants analysed (full cohort)", e["n_sampled"], "quality_full.json: summary.ecg.n_sampled")
        a.note("Mean QTc (ms)", e["mean_qtc"], "quality_full.json: summary.ecg.mean_qtc")
    n_c, n_e = (c or {}).get("n_sampled", "--"), (e or {}).get("n_sampled", "--")
    a.tex("tab_quality.tex", f"""\\begin{{table}}[t]
\\centering
\\caption{{Signal quality on the full cohort (CGM $n={n_c}$, ECG $n={n_e}$) versus the head-slice
(first 200 CGM / 150 ECG participants) used previously. Brackets: 95\\% Wilson CI; $p$: two-proportion
$z$-test, head-slice vs.\\ full cohort.}}
\\label{{tab:quality}}
\\resizebox{{\\columnwidth}}{{!}}{{%
\\begin{{tabular}}{{@{{}} l c c c @{{}}}}
\\hline
\\textbf{{Metric (\\%)}} & \\textbf{{Head-slice}} & \\textbf{{Full cohort [95\\% CI]}} & \\textbf{{$p$}} \\\\
\\hline
{chr(10).join(rows)}
\\hline
\\end{{tabular}}}}
\\end{{table}}
""")


# ── Date audit ───────────────────────────────────────────────────────────────

def date_audit(a: Assets) -> None:
    d = read_json("ecg_date_audit.json")
    if not d:
        print("  skip date audit (run ecg_date_audit.py)")
        return
    ex, dist, off, interp = d["extraction"], d["date_distribution"], d["offsets"], d["validation_date_interpretation"]
    tau = off["tau_days"]
    within = lambda key: sum(b["k"] for b in off[key]["overall"]["bins"] if b["bin"] in ("same day", "1–7 d"))  # noqa: E731
    nn = lambda key: off[key]["overall"]["n"]  # noqa: E731
    from services.readiness_service import proportion
    ecg_w, cgm_w = proportion(within("ecg_minus_visit"), nn("ecg_minus_visit")), proportion(within("cgm_minus_visit"), nn("cgm_minus_visit"))
    mv = d.get("manual_verification")
    rows = [
        f"Headers readable & {ex['n_header_readable']} of {ex['n_hea_found']} \\\\",
        f"\\texttt{{validation\\_date}} extracted & {fmt(ex['date_extracted']['pct'])}\\,\\% {ci(ex['date_extracted']['ci95'])} \\\\",
        f"\\texttt{{base\\_date}} populated & {fmt(ex['base_date_populated']['pct'])}\\,\\% \\\\",
        f"Parser correct (manual, $n={mv['n_scored']}$) & {fmt(mv['both_correct']['pct'])}\\,\\% {ci(mv['both_correct']['ci95'])}, $\\kappa={mv['cohens_kappa']}$ \\\\"
        if mv else "Parser correct (manual check) & pending \\\\",
        f"Distinct ECG dates & {dist['n_distinct']} of {dist['n_dates']} (top: {fmt(dist['share_top_1_pct'])}\\,\\%) \\\\",
        f"ECG within $\\pm{tau}$\\,d of visit & {fmt(ecg_w['pct'])}\\,\\% {ci(ecg_w['ci95'])} \\\\",
        f"CGM start within $\\pm{tau}$\\,d of visit & {fmt(cgm_w['pct'])}\\,\\% {ci(cgm_w['ci95'])} \\\\",
        f"ECG and CGM both within $\\pm{tau}$\\,d & {fmt(off['ecg_and_cgm_within_tau_of_visit']['pct'])}\\,\\% "
        f"{ci(off['ecg_and_cgm_within_tau_of_visit']['ci95'])} \\\\",
    ]
    a.note("validation_date extraction coverage", f"{ex['date_extracted']['pct']}% of {ex['n_header_readable']}",
           "ecg_date_audit.json: extraction.date_extracted")
    a.note("base_date populated", f"{ex['base_date_populated']['pct']}%", "ecg_date_audit.json: extraction.base_date_populated")
    a.note("Distinct validation_date values", f"{dist['n_distinct']} of {dist['n_dates']}", "ecg_date_audit.json: date_distribution")
    a.note(f"ECG within ±{tau} d of visit", f"{ecg_w['pct']}% {ci(ecg_w['ci95'])}", "ecg_date_audit.json: offsets.ecg_minus_visit")
    a.note(f"CGM within ±{tau} d of visit", f"{cgm_w['pct']}% {ci(cgm_w['ci95'])}", "ecg_date_audit.json: offsets.cgm_minus_visit")
    a.note("validation_date heuristic reading", interp["verdict"], "ecg_date_audit.json: validation_date_interpretation")
    if mv:
        a.note("Manual parser verification (both reviewers)", f"{mv['both_correct']['pct']}%, kappa {mv['cohens_kappa']}",
               "ecg_date_audit.json: manual_verification")
    a.tex("tab_date_audit.tex", f"""\\begin{{table}}[t]
\\centering
\\caption{{ECG date recovery: extraction, parser verification and temporal co-registration with the
clinical visit (calendar-date granularity). Brackets: 95\\% Wilson CI.}}
\\label{{tab:dateaudit}}
\\begin{{tabular}}{{@{{}} l l @{{}}}}
\\hline
\\textbf{{Check}} & \\textbf{{Result}} \\\\
\\hline
{chr(10).join(rows)}
\\hline
\\end{{tabular}}
\\end{{table}}
""")

    plt = plt_setup()
    series = [("ECG − visit", "ecg_minus_visit", "0.25", ""), ("CGM − visit", "cgm_minus_visit", "0.6", ""),
              ("ECG − CGM", "ecg_minus_cgm", "0.9", "//")]
    labels = [b["bin"] for b in off["ecg_minus_visit"]["overall"]["bins"]]
    fig, ax = plt.subplots(figsize=(3.4, 1.9))
    w = 0.26
    for i, (name, key, color, hatch) in enumerate(series):
        vals = [b["pct"] or 0 for b in off[key]["overall"]["bins"]]
        ax.bar([x + (i - 1) * w for x in range(len(labels))], vals, w, label=f"{name} (n={off[key]['overall']['n']})",
               color=color, edgecolor="black", linewidth=0.4, hatch=hatch)
    ax.set_xticks(range(len(labels)), labels)
    ax.set_ylabel("Participants (%)")
    ax.set_xlabel("|offset|")
    ax.legend(frameon=False, fontsize=6.5)
    a.fig(fig, "fig_offsets.pdf")
    plt.close(fig)


# ── Gating ───────────────────────────────────────────────────────────────────

def gating(a: Assets) -> None:
    g = read_json("gating_results.json")
    if not g:
        print("  skip gating (run gating_experiment.py)")
        return
    dx = g["tasks"]["diagnosis_t2d"]
    rg = g["tasks"].get("hba1c_regression", {})
    rows = []
    for gate in ("G0", "G1", "G2", "G3"):
        cells = [gate, str(dx["conditions"]["logreg"][gate]["n_train"])]
        for kind in ("logreg", "hgb"):
            tc = dx["conditions"][kind][gate].get("test_clean", {})
            cells.append(f"{fmt(tc.get('auroc'), 3)} {ci(tc.get('auroc_ci95'))}")
        mae = rg.get("conditions", {}).get("hgb", {}).get(gate, {}).get("test_clean", {}).get("mae")
        cells.append(fmt(mae, 3))
        rows.append(" & ".join(cells) + " \\\\")
        for kind in ("logreg", "hgb"):
            tc = dx["conditions"][kind][gate].get("test_clean", {})
            a.note(f"AUROC {kind} trained on {gate} (test_clean)", f"{tc.get('auroc')} {ci(tc.get('auroc_ci95'))}",
                   f"gating_results.json: tasks.diagnosis_t2d.conditions.{kind}.{gate}.test_clean")
    rand_cells = ["G3-rand", str(dx["g3_rand"]["logreg"]["n_train"])]
    for kind in ("logreg", "hgb"):
        r = dx["g3_rand"][kind]
        rand_cells.append(f"{fmt(r['mean'], 3)} $\\pm$ {fmt(r['sd'], 3)}")
    rand_cells.append("--")
    rows.append(" & ".join(rand_cells) + " \\\\")
    for kind in ("logreg", "hgb"):
        d = dx["paired_g3_minus_g0"].get(kind)
        if d:
            a.note(f"AUROC difference G3 − G0 ({kind}, paired bootstrap)", f"{d['difference']} {ci(d['ci95'])}",
                   f"gating_results.json: tasks.diagnosis_t2d.paired_g3_minus_g0.{kind}")
    n_clean = dx["eval_sets"]["test_clean"]
    a.tex("tab_gating.tex", f"""\\begin{{table}}[t]
\\centering
\\caption{{T2D diagnosis from ECG + CGM + clinical features when training on each readiness gate,
evaluated on the same clean test set ($n={n_clean}$). AUROC [95\\% bootstrap CI]; G3-rand: random
subsets of G0 with the size of G3 (mean $\\pm$ SD, {dx['g3_rand']['logreg']['repeats']} draws).
MAE: HbA1c regression (\\%), gradient boosting.}}
\\label{{tab:gating}}
\\resizebox{{\\columnwidth}}{{!}}{{%
\\begin{{tabular}}{{@{{}} l r c c c @{{}}}}
\\hline
\\textbf{{Train set}} & \\textbf{{$n$}} & \\textbf{{AUROC (LR)}} & \\textbf{{AUROC (GBM)}} & \\textbf{{MAE}} \\\\
\\hline
{chr(10).join(rows)}
\\hline
\\end{{tabular}}}}
\\end{{table}}
""")

    abl_rows = []
    for name, m in dx["ablation_g3"].get("hgb", {}).items():
        lr = dx["ablation_g3"].get("logreg", {}).get(name, {})
        abl_rows.append(f"{name} & {fmt(lr.get('auroc'), 3)} {ci(lr.get('auroc_ci95'))} & "
                        f"{fmt(m.get('auroc'), 3)} {ci(m.get('auroc_ci95'))} \\\\")
    a.tex("tab_ablation.tex", f"""\\begin{{table}}[t]
\\centering
\\caption{{Modality ablation for T2D diagnosis, trained on G3, clean test set. AUROC [95\\% CI].}}
\\label{{tab:ablation}}
\\begin{{tabular}}{{@{{}} l c c @{{}}}}
\\hline
\\textbf{{Modalities}} & \\textbf{{LR}} & \\textbf{{GBM}} \\\\
\\hline
{chr(10).join(abl_rows)}
\\hline
\\end{{tabular}}
\\end{{table}}
""")

    plt = plt_setup()
    fig, ax = plt.subplots(figsize=(3.4, 1.9))
    gates = ["G0", "G1", "G2", "G3"]
    for kind, marker, off in (("logreg", "o", -0.08), ("hgb", "s", 0.08)):
        ys, lo, hi = [], [], []
        for gate in gates:
            tc = dx["conditions"][kind][gate].get("test_clean", {})
            y = tc.get("auroc")
            c_ = tc.get("auroc_ci95") or [None, None]
            ys.append(y if y is not None else float("nan"))
            lo.append((y - c_[0]) if y is not None and c_[0] is not None else 0)
            hi.append((c_[1] - y) if y is not None and c_[1] is not None else 0)
        ax.errorbar([i + off for i in range(4)], ys, yerr=[lo, hi], fmt=marker, color="black",
                    capsize=2, markersize=3.5, linewidth=0.8, label={"logreg": "LR", "hgb": "GBM"}[kind])
        r = dx["g3_rand"][kind]
        if r["mean"] is not None and r["sd"] is not None:
            ax.axhspan(r["mean"] - r["sd"], r["mean"] + r["sd"], xmin=0.78, xmax=0.98,
                       color="0.85" if kind == "logreg" else "0.7", alpha=0.5, zorder=0)
    ax.set_xticks(range(4), ["G0\nnone", "G1\ncoverage", "G2\n+integrity", "G3\n+temporal"])
    ax.set_ylabel("AUROC (clean test)")
    ax.legend(frameon=False, fontsize=6.5, loc="lower left")
    a.fig(fig, "fig_gating.pdf")
    plt.close(fig)

    att = g["attrition"]
    fig, ax = plt.subplots(figsize=(3.4, 1.8))
    styles = ["-", "--", "-.", ":"]
    for i, (grp, short) in enumerate(GROUP_SHORT.items()):
        ys = [row["by_group"].get(grp, {}).get("pct_of_G0") for row in att["funnel_all_splits"]]
        ax.plot(range(4), [y if y is not None else float("nan") for y in ys], styles[i], marker="o",
                color="black", markersize=3, linewidth=0.9, label=short)
    ax.set_xticks(range(4), ["G0", "G1", "G2", "G3"])
    ax.set_ylabel("Retained (% of G0)")
    ax.legend(frameon=False, fontsize=6.5, ncol=2)
    a.fig(fig, "fig_funnel.pdf")
    plt.close(fig)
    if att.get("retention_by_group_pct"):
        a.note("Retention G3/G0 by group (%)", att["retention_by_group_pct"], "gating_results.json: attrition.retention_by_group_pct")
        a.note("Retention differs by group (chi-square p)", att.get("retention_chi2", {}).get("p_value"),
               "gating_results.json: attrition.retention_chi2")


# ── Benchmark and usability ──────────────────────────────────────────────────

def benchmark(a: Assets) -> None:
    b = read_json("benchmark.json")
    if not b:
        print("  skip benchmark (run benchmark_api.py)")
        return
    rows = []
    for label, s in b["steps"].items():
        if s.get("status") != 200:
            continue
        rows.append(f"{label} & {fmt(s['cold']['mean_s'], 2)} $\\pm$ {fmt(s['cold']['sd_s'], 2)} & "
                    f"{fmt(s['warm']['mean_s'], 3)} \\\\")
        a.note(f"API {label}: cold / warm (s)", f"{s['cold']['mean_s']} / {s['warm']['mean_s']}", f"benchmark.json: steps.{label}")
    m = b.get("manual_baseline")
    if m:
        rows.append(f"Manual baseline ({m['analysis_loc']} LOC) & {fmt(m['wall_clock']['mean_s'], 2)} $\\pm$ "
                    f"{fmt(m['wall_clock']['sd_s'], 2)} & -- \\\\")
        a.note("Manual baseline lines of code", m["analysis_loc"], "benchmark.json: manual_baseline.analysis_loc")
        a.note("Manual baseline wall-clock (s)", m["wall_clock"]["mean_s"], "benchmark.json: manual_baseline.wall_clock")
    if b.get("offline_pipeline_cost_s") is not None:
        a.note("One-off full-cohort pipeline cost (s)", b["offline_pipeline_cost_s"], "benchmark.json: offline_pipeline_cost_s")
    hw = b["hardware"]
    a.tex("tab_benchmark.tex", f"""\\begin{{table}}[t]
\\centering
\\caption{{Measured response time per workflow step ({b['repeats']} repeats; cold = caches cleared)
on {hw['cpu_count']} vCPU / {hw['mem_gib']}\\,GiB. Manual baseline: notebook-equivalent script from raw files.}}
\\label{{tab:benchmark}}
\\resizebox{{\\columnwidth}}{{!}}{{%
\\begin{{tabular}}{{@{{}} l c c @{{}}}}
\\hline
\\textbf{{Step}} & \\textbf{{Cold (s)}} & \\textbf{{Warm (s)}} \\\\
\\hline
{chr(10).join(rows)}
\\hline
\\end{{tabular}}}}
\\end{{table}}
""")


def usability(a: Assets) -> None:
    u = read_json("usability.json")
    if not u:
        print("  skip usability (run score_usability.py)")
        return
    rows = [f"{i}. {t['task']} & {fmt(t['time_s']['mean'])} $\\pm$ {fmt(t['time_s']['sd'])} & "
            f"{fmt(t['success_unaided']['pct'])} \\\\" for i, t in enumerate(u["tasks"].values(), 1)]
    a.note("Usability participants", u["n_participants"], "usability.json: n_participants")
    a.note("SUS mean ± SD", f"{u['sus']['mean']} ± {u['sus']['sd']}", "usability.json: sus")
    a.tex("tab_usability.tex", f"""\\begin{{table}}[t]
\\centering
\\caption{{Formative usability study ($N={u['n_participants']}$): time for unaided successes and
unaided success rate per task. SUS ${fmt(u['sus']['mean'])} \\pm {fmt(u['sus']['sd'])}$.}}
\\label{{tab:usability}}
\\begin{{tabular}}{{@{{}} l c c @{{}}}}
\\hline
\\textbf{{Task}} & \\textbf{{Time (s)}} & \\textbf{{Success (\\%)}} \\\\
\\hline
{chr(10).join(rows)}
\\hline
\\end{{tabular}}
\\end{{table}}
""")


def main() -> None:
    from _common import dataset_is_synthetic

    banner("Paper assets")
    a = Assets()
    a.synthetic = dataset_is_synthetic()
    for step in (quality, date_audit, gating, benchmark, usability):
        step(a)
    lines = ["# Numbers used in the paper", "",
             "Every value below is produced by a script in `scripts/`; cite the source when editing the paper.", ""]
    if a.synthetic:
        lines += ["> **SYNTHETIC TEST DATA — these are not AI-READI results.**", ""]
    lines += ["| Claim | Value | Source (results/…) |", "| --- | --- | --- |"]
    lines += [f"| {c} | {v} | `{s}` |" for c, v, s in a.numbers]
    (a.dir / "numbers.md").write_text("\n".join(lines) + "\n")
    print(f"  wrote numbers.md ({len(a.numbers)} entries)\nAssets in {a.dir}")


if __name__ == "__main__":
    main()
